set(SEVEN_ZIP_C_SOURCE_FILES
	7zAlloc.c
	7zAlloc.h
	7zArcIn.c
	7zBuf2.c
	7zBuf.c
	7zBuf.h
	7zCrcOpt.c
	7zCrc.c
	7zCrc.h
	7zDec.c
	7zFile.c
	7zFile.h
	7zStream.c
	7zTypes.h
	7zVersion.h
	7z.h
	AesOpt.c
	Aes.c
	Aes.h
	Alloc.c
	Alloc.h
	Bcj2Enc.c
	Bcj2.c
	Bcj2.h
	Blake2s.c
	Blake2.h
	Bra86.c
	BraIA64.c
	Bra.c
	Bra.h
	BwtSort.c
	BwtSort.h
	Compiler.h
	CpuArch.c
	CpuArch.h
	Delta.c
	Delta.h
	DllSecur.c
	DllSecur.h
	HuffEnc.c
	HuffEnc.h
	LzFindMt.c
	LzFindMt.h
	LzFindOpt.c
	LzFind.c
	LzFind.h
	LzHash.h
	Lzma2DecMt.c
	Lzma2DecMt.h
	Lzma2Dec.c
	Lzma2Dec.h
	Lzma2Enc.c
	Lzma2Enc.h
	Lzma86Dec.c
	Lzma86Enc.c
	Lzma86.h
	LzmaDec.c
	LzmaDec.h
	LzmaEnc.c
	LzmaEnc.h
	LzmaLib.c
	LzmaLib.h
	MtCoder.c
	MtCoder.h
	MtDec.c
	MtDec.h
	Ppmd7aDec.c
	Ppmd7Dec.c
	Ppmd7Enc.c
	Ppmd7.c
	Ppmd7.h
	Ppmd8Dec.c
	Ppmd8Enc.c
	Ppmd8.c
	Ppmd8.h
	Ppmd.h
	Precomp.h
	RotateDefs.h
	Sha1Opt.c
	Sha1.c
	Sha1.h
	Sha256Opt.c
	Sha256.c
	Sha256.h
	Sort.c
	Sort.h
	Threads.c
	Threads.h
	XzCrc64Opt.c
	XzCrc64.c
	XzCrc64.h
	XzDec.c
	XzEnc.c
	XzEnc.h
	XzIn.c
	Xz.c
	Xz.h
)

set(SEVEN_ZIP_CPP_SOURCE_FILES
	7zip/ICoder.h
	7zip/IDecl.h
	7zip/IPassword.h
	7zip/IProgress.h
	7zip/IStream.h
	7zip/PropID.h
	7zip/Archive/ApmHandler.cpp
	7zip/Archive/ApmHandler.h
	7zip/Archive/ArHandler.cpp
	7zip/Archive/ArHandler.h
	7zip/Archive/ArjHandler.cpp
	7zip/Archive/ArjHandler.h
	7zip/Archive/Base64Handler.cpp
	7zip/Archive/Base64Handler.h
	7zip/Archive/Bz2Handler.cpp
	7zip/Archive/Bz2Handler.h
	7zip/Archive/ComHandler.cpp
	7zip/Archive/ComHandler.h
	7zip/Archive/CpioHandler.cpp
	7zip/Archive/CpioHandler.h
	7zip/Archive/CramfsHandler.cpp
	7zip/Archive/CramfsHandler.h
	7zip/Archive/DeflateProps.cpp
	7zip/Archive/DeflateProps.h
	7zip/Archive/DmgHandler.cpp
	7zip/Archive/DmgHandler.h
	7zip/Archive/ElfHandler.cpp
	7zip/Archive/ElfHandler.h
	7zip/Archive/ExtHandler.cpp
	7zip/Archive/ExtHandler.h
	7zip/Archive/FatHandler.cpp
	7zip/Archive/FatHandler.h
	7zip/Archive/FlvHandler.cpp
	7zip/Archive/FlvHandler.h
	7zip/Archive/GptHandler.cpp
	7zip/Archive/GptHandler.h
	7zip/Archive/GzHandler.cpp
	7zip/Archive/GzHandler.h
	7zip/Archive/HandlerCont.cpp
	7zip/Archive/HandlerCont.h
	7zip/Archive/HfsHandler.cpp
	7zip/Archive/HfsHandler.h
	7zip/Archive/IArchive.h
	7zip/Archive/IhexHandler.cpp
	7zip/Archive/IhexHandler.h
	7zip/Archive/LzhHandler.cpp
	7zip/Archive/LzhHandler.h
	7zip/Archive/LzmaHandler.cpp
	7zip/Archive/LzmaHandler.h
	7zip/Archive/MachoHandler.cpp
	7zip/Archive/MachoHandler.h
	7zip/Archive/MbrHandler.cpp
	7zip/Archive/MbrHandler.h
	7zip/Archive/MslzHandler.cpp
	7zip/Archive/MslzHandler.h
	7zip/Archive/MubHandler.cpp
	7zip/Archive/MubHandler.h
	7zip/Archive/NtfsHandler.cpp
	7zip/Archive/NtfsHandler.h
	7zip/Archive/PeHandler.cpp
	7zip/Archive/PeHandler.h
	7zip/Archive/PpmdHandler.cpp
	7zip/Archive/PpmdHandler.h
	7zip/Archive/QcowHandler.cpp
	7zip/Archive/QcowHandler.h
	7zip/Archive/RpmHandler.cpp
	7zip/Archive/RpmHandler.h
	7zip/Archive/SplitHandler.cpp
	7zip/Archive/SplitHandler.h
	7zip/Archive/SquashfsHandler.cpp
	7zip/Archive/SquashfsHandler.h
	7zip/Archive/StdAfx.h
	7zip/Archive/SwfHandler.cpp
	7zip/Archive/SwfHandler.h
	7zip/Archive/UefiHandler.cpp
	7zip/Archive/UefiHandler.h
	7zip/Archive/VdiHandler.cpp
	7zip/Archive/VdiHandler.h
	7zip/Archive/VhdHandler.cpp
	7zip/Archive/VhdHandler.h
	7zip/Archive/VhdxHandler.cpp
	7zip/Archive/VhdxHandler.h
	7zip/Archive/VmdkHandler.cpp
	7zip/Archive/VmdkHandler.h
	7zip/Archive/XarHandler.cpp
	7zip/Archive/XarHandler.h
	7zip/Archive/XzHandler.cpp
	7zip/Archive/XzHandler.h
	7zip/Archive/XzHandler.h
	7zip/Archive/ZHandler.cpp
	7zip/Archive/ZHandler.h
	7zip/Archive/Common/CoderMixer2.cpp
	7zip/Archive/Common/CoderMixer2.h
	7zip/Archive/Common/DummyOutStream.cpp
	7zip/Archive/Common/DummyOutStream.h
	7zip/Archive/Common/FindSignature.cpp
	7zip/Archive/Common/FindSignature.h
	7zip/Archive/Common/HandlerOut.cpp
	7zip/Archive/Common/HandlerOut.h
	7zip/Archive/Common/InStreamWithCRC.cpp
	7zip/Archive/Common/InStreamWithCRC.h
	7zip/Archive/Common/ItemNameUtils.cpp
	7zip/Archive/Common/ItemNameUtils.h
	7zip/Archive/Common/MultiStream.cpp
	7zip/Archive/Common/MultiStream.h
	7zip/Archive/Common/OutStreamWithCRC.cpp
	7zip/Archive/Common/OutStreamWithCRC.h
	7zip/Archive/Common/OutStreamWithSha1.cpp
	7zip/Archive/Common/OutStreamWithSha1.h
	7zip/Archive/Common/ParseProperties.cpp
	7zip/Archive/Common/ParseProperties.h
	7zip/Archive/Common/StdAfx.h
	7zip/Archive/7z/7zCompressionMode.cpp
	7zip/Archive/7z/7zCompressionMode.h
	7zip/Archive/7z/7zDecode.cpp
	7zip/Archive/7z/7zDecode.h
	7zip/Archive/7z/7zEncode.cpp
	7zip/Archive/7z/7zEncode.h
	7zip/Archive/7z/7zExtract.cpp
	7zip/Archive/7z/7zFolderInStream.cpp
	7zip/Archive/7z/7zFolderInStream.h
	7zip/Archive/7z/7zHandlerOut.cpp
	7zip/Archive/7z/7zHandler.cpp
	7zip/Archive/7z/7zHandler.h
	7zip/Archive/7z/7zHeader.cpp
	7zip/Archive/7z/7zHeader.h
	7zip/Archive/7z/7zIn.cpp
	7zip/Archive/7z/7zIn.h
	7zip/Archive/7z/7zItem.h
	7zip/Archive/7z/7zOut.cpp
	7zip/Archive/7z/7zOut.h
	7zip/Archive/7z/7zProperties.cpp
	7zip/Archive/7z/7zProperties.h
	7zip/Archive/7z/7zRegister.cpp
	7zip/Archive/7z/7zSpecStream.cpp
	7zip/Archive/7z/7zSpecStream.h
	7zip/Archive/7z/7zUpdate.cpp
	7zip/Archive/7z/7zUpdate.h
	7zip/Archive/7z/StdAfx.cpp
	7zip/Archive/7z/StdAfx.h
	7zip/Archive/Cab/CabBlockInStream.cpp
	7zip/Archive/Cab/CabBlockInStream.h
	7zip/Archive/Cab/CabHandler.cpp
	7zip/Archive/Cab/CabHandler.h
	7zip/Archive/Cab/CabHeader.cpp
	7zip/Archive/Cab/CabHeader.h
	7zip/Archive/Cab/CabIn.cpp
	7zip/Archive/Cab/CabIn.h
	7zip/Archive/Cab/CabItem.h
	7zip/Archive/Cab/CabRegister.cpp
	7zip/Archive/Cab/StdAfx.h
	7zip/Archive/Chm/ChmHandler.cpp
	7zip/Archive/Chm/ChmHandler.h
	7zip/Archive/Chm/ChmIn.cpp
	7zip/Archive/Chm/ChmIn.h
	7zip/Archive/Chm/StdAfx.h
	7zip/Archive/Iso/IsoHandler.cpp
	7zip/Archive/Iso/IsoHandler.h
	7zip/Archive/Iso/IsoHeader.cpp
	7zip/Archive/Iso/IsoHeader.h
	7zip/Archive/Iso/IsoIn.cpp
	7zip/Archive/Iso/IsoIn.h
	7zip/Archive/Iso/IsoItem.h
	7zip/Archive/Iso/IsoRegister.cpp
	7zip/Archive/Iso/StdAfx.h
	7zip/Archive/Nsis/NsisDecode.cpp
	7zip/Archive/Nsis/NsisDecode.h
	7zip/Archive/Nsis/NsisHandler.cpp
	7zip/Archive/Nsis/NsisHandler.h
	7zip/Archive/Nsis/NsisIn.cpp
	7zip/Archive/Nsis/NsisIn.h
	7zip/Archive/Nsis/NsisRegister.cpp
	7zip/Archive/Nsis/StdAfx.h
	7zip/Archive/Rar/Rar5Handler.cpp
	7zip/Archive/Rar/Rar5Handler.h
	7zip/Archive/Rar/RarHandler.cpp
	7zip/Archive/Rar/RarHandler.h
	7zip/Archive/Rar/RarHeader.h
	7zip/Archive/Rar/RarItem.h
	7zip/Archive/Rar/RarVol.h
	7zip/Archive/Rar/StdAfx.cpp
	7zip/Archive/Rar/StdAfx.h
	7zip/Archive/Tar/StdAfx.h
	7zip/Archive/Tar/TarHandlerOut.cpp
	7zip/Archive/Tar/TarHandler.cpp
	7zip/Archive/Tar/TarHandler.h
	7zip/Archive/Tar/TarHeader.cpp
	7zip/Archive/Tar/TarHeader.h
	7zip/Archive/Tar/TarIn.cpp
	7zip/Archive/Tar/TarIn.h
	7zip/Archive/Tar/TarItem.h
	7zip/Archive/Tar/TarOut.cpp
	7zip/Archive/Tar/TarOut.h
	7zip/Archive/Tar/TarRegister.cpp
	7zip/Archive/Tar/TarUpdate.cpp
	7zip/Archive/Tar/TarUpdate.h
	7zip/Archive/Udf/StdAfx.h
	7zip/Archive/Udf/UdfHandler.cpp
	7zip/Archive/Udf/UdfHandler.h
	7zip/Archive/Udf/UdfIn.cpp
	7zip/Archive/Udf/UdfIn.h
	7zip/Archive/Wim/StdAfx.h
	7zip/Archive/Wim/WimHandlerOut.cpp
	7zip/Archive/Wim/WimHandler.cpp
	7zip/Archive/Wim/WimHandler.h
	7zip/Archive/Wim/WimIn.cpp
	7zip/Archive/Wim/WimIn.h
	7zip/Archive/Wim/WimRegister.cpp
	7zip/Archive/Zip/StdAfx.h
	7zip/Archive/Zip/ZipAddCommon.cpp
	7zip/Archive/Zip/ZipAddCommon.h
	7zip/Archive/Zip/ZipCompressionMode.h
	7zip/Archive/Zip/ZipHandlerOut.cpp
	7zip/Archive/Zip/ZipHandler.cpp
	7zip/Archive/Zip/ZipHandler.h
	7zip/Archive/Zip/ZipHeader.h
	7zip/Archive/Zip/ZipIn.cpp
	7zip/Archive/Zip/ZipIn.h
	7zip/Archive/Zip/ZipItem.cpp
	7zip/Archive/Zip/ZipItem.h
	7zip/Archive/Zip/ZipOut.cpp
	7zip/Archive/Zip/ZipOut.h
	7zip/Archive/Zip/ZipRegister.cpp
	7zip/Archive/Zip/ZipUpdate.cpp
	7zip/Archive/Zip/ZipUpdate.h
	7zip/Common/CreateCoder.cpp
	7zip/Common/CreateCoder.h
	7zip/Common/CWrappers.cpp
	7zip/Common/CWrappers.h
	7zip/Common/FilePathAutoRename.cpp
	7zip/Common/FilePathAutoRename.h
	7zip/Common/FileStreams.cpp
	7zip/Common/FileStreams.h
	7zip/Common/FilterCoder.cpp
	7zip/Common/FilterCoder.h
	7zip/Common/ILibrary.cpp
	7zip/Common/ILibrary.h
	7zip/Common/InBuffer.cpp
	7zip/Common/InBuffer.h
	7zip/Common/InOutTempBuffer.cpp
	7zip/Common/InOutTempBuffer.h
	7zip/Common/LimitedStreams.cpp
	7zip/Common/LimitedStreams.h
	7zip/Common/LockedStream.cpp
	7zip/Common/LockedStream.h
	7zip/Common/MemBlocks.cpp
	7zip/Common/MemBlocks.h
	7zip/Common/MethodId.cpp
	7zip/Common/MethodId.h
	7zip/Common/MethodProps.cpp
	7zip/Common/MethodProps.h
	7zip/Common/OffsetStream.cpp
	7zip/Common/OffsetStream.h
	7zip/Common/OutBuffer.cpp
	7zip/Common/OutBuffer.h
	7zip/Common/OutMemStream.cpp
	7zip/Common/OutMemStream.h
	7zip/Common/ProgressMt.cpp
	7zip/Common/ProgressMt.h
	7zip/Common/ProgressUtils.cpp
	7zip/Common/ProgressUtils.h
	7zip/Common/PropId.cpp
	7zip/Common/RegisterArc.h
	7zip/Common/RegisterCodec.h
	7zip/Common/StdAfx.h
	7zip/Common/StreamBinder.cpp
	7zip/Common/StreamBinder.h
	7zip/Common/StreamObjects.cpp
	7zip/Common/StreamObjects.h
	7zip/Common/StreamUtils.cpp
	7zip/Common/StreamUtils.h
	7zip/Common/UniqBlocks.cpp
	7zip/Common/UniqBlocks.h
	7zip/Common/VirtThread.cpp
	7zip/Common/VirtThread.h
	7zip/Compress/Bcj2Coder.cpp
	7zip/Compress/Bcj2Coder.h
	7zip/Compress/Bcj2Register.cpp
	7zip/Compress/BcjCoder.cpp
	7zip/Compress/BcjCoder.h
	7zip/Compress/BcjRegister.cpp
	7zip/Compress/BitlDecoder.cpp
	7zip/Compress/BitlDecoder.h
	7zip/Compress/BitlEncoder.h
	7zip/Compress/BitmDecoder.h
	7zip/Compress/BitmEncoder.h
	7zip/Compress/BranchMisc.cpp
	7zip/Compress/BranchMisc.h
	7zip/Compress/BranchRegister.cpp
	7zip/Compress/ByteSwap2Filter.cpp
	7zip/Compress/ByteSwap2Filter.h
	7zip/Compress/ByteSwap4Filter.cpp
	7zip/Compress/ByteSwap4Filter.h
	7zip/Compress/ByteSwap.cpp
	7zip/Compress/BZip2Const.h
	7zip/Compress/BZip2Crc.cpp
	7zip/Compress/BZip2Crc.h
	7zip/Compress/BZip2Decoder.cpp
	7zip/Compress/BZip2Decoder.h
	7zip/Compress/BZip2Encoder.cpp
	7zip/Compress/BZip2Encoder.h
	7zip/Compress/BZip2Register.cpp
	7zip/Compress/CopyCoder.cpp
	7zip/Compress/CopyCoder.h
	7zip/Compress/CopyRegister.cpp
	7zip/Compress/Deflate64Register.cpp
	7zip/Compress/DeflateConst.h
	7zip/Compress/DeflateDecoder.cpp
	7zip/Compress/DeflateDecoder.h
	7zip/Compress/DeflateEncoder.cpp
	7zip/Compress/DeflateEncoder.h
	7zip/Compress/DeflateRegister.cpp
	7zip/Compress/DeltaFilterReg.cpp
	7zip/Compress/DeltaFilter.cpp
	7zip/Compress/DeltaFilter.h
	7zip/Compress/HuffmanDecoder.h
	7zip/Compress/ImplodeDecoder.cpp
	7zip/Compress/ImplodeDecoder.h
	7zip/Compress/ImplodeHuffmanDecoder.cpp
	7zip/Compress/ImplodeHuffmanDecoder.h
	7zip/Compress/LzfseDecoder.cpp
	7zip/Compress/LzfseDecoder.h
	7zip/Compress/LzhDecoder.cpp
	7zip/Compress/LzhDecoder.h
	7zip/Compress/Lzma2Decoder.cpp
	7zip/Compress/Lzma2Decoder.h
	7zip/Compress/Lzma2Encoder.cpp
	7zip/Compress/Lzma2Encoder.h
	7zip/Compress/Lzma2Register.cpp
	7zip/Compress/LzmaDecoder.cpp
	7zip/Compress/LzmaDecoder.h
	7zip/Compress/LzmaEncoder.cpp
	7zip/Compress/LzmaEncoder.h
	7zip/Compress/LzmaRegister.cpp
	7zip/Compress/LzmsDecoder.cpp
	7zip/Compress/LzmsDecoder.h
	7zip/Compress/LzOutWindow.cpp
	7zip/Compress/LzOutWindow.h
	7zip/Compress/LzxDecoder.cpp
	7zip/Compress/LzxDecoder.h
	7zip/Compress/Lzx.h
	7zip/Compress/Mtf8.h
	7zip/Compress/PpmdDecoder.cpp
	7zip/Compress/PpmdDecoder.h
	7zip/Compress/PpmdEncoder.cpp
	7zip/Compress/PpmdEncoder.h
	7zip/Compress/PpmdRegister.cpp
	7zip/Compress/PpmdZip.cpp
	7zip/Compress/PpmdZip.h
	7zip/Compress/QuantumDecoder.cpp
	7zip/Compress/QuantumDecoder.h
	7zip/Compress/Rar1Decoder.cpp
	7zip/Compress/Rar1Decoder.h
	7zip/Compress/Rar2Decoder.cpp
	7zip/Compress/Rar2Decoder.h
	7zip/Compress/Rar3Decoder.cpp
	7zip/Compress/Rar3Decoder.h
	7zip/Compress/Rar3Vm.cpp
	7zip/Compress/Rar3Vm.h
	7zip/Compress/Rar5Decoder.cpp
	7zip/Compress/Rar5Decoder.h
	7zip/Compress/RarCodecsRegister.cpp
	7zip/Compress/ShrinkDecoder.cpp
	7zip/Compress/ShrinkDecoder.h
	7zip/Compress/StdAfx.h
	7zip/Compress/XpressDecoder.cpp
	7zip/Compress/XpressDecoder.h
	7zip/Compress/XzDecoder.cpp
	7zip/Compress/XzDecoder.h
	7zip/Compress/XzEncoder.cpp
	7zip/Compress/XzEncoder.h
	7zip/Compress/ZDecoder.cpp
	7zip/Compress/ZDecoder.h
	7zip/Compress/ZlibDecoder.cpp
	7zip/Compress/ZlibDecoder.h
	7zip/Compress/ZlibEncoder.cpp
	7zip/Compress/ZlibEncoder.h
	7zip/Crypto/7zAesRegister.cpp
	7zip/Crypto/7zAes.cpp
	7zip/Crypto/7zAes.h
	7zip/Crypto/HmacSha1.cpp
	7zip/Crypto/HmacSha1.h
	7zip/Crypto/HmacSha256.cpp
	7zip/Crypto/HmacSha256.h
	7zip/Crypto/MyAesReg.cpp
	7zip/Crypto/MyAes.cpp
	7zip/Crypto/MyAes.h
	7zip/Crypto/Pbkdf2HmacSha1.cpp
	7zip/Crypto/Pbkdf2HmacSha1.h
	7zip/Crypto/RandGen.cpp
	7zip/Crypto/RandGen.h
	7zip/Crypto/Rar5Aes.cpp
	7zip/Crypto/Rar5Aes.h
	7zip/Crypto/Rar20Crypto.cpp
	7zip/Crypto/Rar20Crypto.h
	7zip/Crypto/RarAes.cpp
	7zip/Crypto/RarAes.h
	7zip/Crypto/Sha1Cls.h
	7zip/Crypto/StdAfx.h
	7zip/Crypto/WzAes.cpp
	7zip/Crypto/WzAes.h
	7zip/Crypto/ZipCrypto.cpp
	7zip/Crypto/ZipCrypto.h
	7zip/Crypto/ZipStrong.cpp
	7zip/Crypto/ZipStrong.h
	Common/AutoPtr.h
	Common/CksumHasher.cpp
	Common/CksumHasher.h
	Common/CksumReg.cpp
	Common/CommandLineParser.cpp
	Common/CommandLineParser.h
	Common/Common.h
	Common/ComTry.h
	Common/CRCHasher.cpp
	Common/CRCHasher.h
	Common/CrcReg.cpp
	Common/CRC.cpp
	Common/C_FileIO.cpp
	Common/C_FileIO.h
	Common/Defs.h
	Common/DynamicBuffer.h
	Common/DynLimBuf.cpp
	Common/DynLimBuf.h
	Common/IntToString.cpp
	Common/IntToString.h
	Common/Lang.cpp
	Common/Lang.h
	Common/ListFileUtils.cpp
	Common/ListFileUtils.h
	Common/LzFindPrepare.cpp
	Common/MyBuffer2.h
	Common/MyBuffer.h
	Common/MyCom.h
	Common/MyException.h
	Common/MyGuidDef.h
	Common/MyInitGuid.h
	Common/MyLinux.h
	Common/MyMap.cpp
	Common/MyMap.h
	Common/MyString.cpp
	Common/MyString.h
	Common/MyTypes.h
	Common/MyUnknown.h
	Common/MyVector.cpp
	Common/MyVector.h
	Common/MyWindows.cpp
	Common/MyWindows.h
	Common/MyXml.cpp
	Common/MyXml.h
	Common/NewHandler.cpp
	Common/NewHandler.h
	Common/Random.cpp
	Common/Random.h
	Common/Sha1Hasher.cpp
	Common/Sha1Hasher.h
	Common/Sha1Prepare.cpp
	Common/Sha1Reg.cpp
	Common/Sha256Hasher.cpp
	Common/Sha256Hasher.h
	Common/Sha256Prepare.cpp
	Common/Sha256Reg.cpp
	Common/StdAfx.h
	Common/StdInStream.cpp
	Common/StdInStream.h
	Common/StdOutStream.cpp
	Common/StdOutStream.h
	Common/StringConvert.cpp
	Common/StringConvert.h
	Common/StringToInt.cpp
	Common/StringToInt.h
	Common/TextConfig.cpp
	Common/TextConfig.h
	Common/UTFConvert.cpp
	Common/UTFConvert.h
	Common/Wildcard.cpp
	Common/Wildcard.h
	Common/XzCrc64Hasher.cpp
	Common/XzCrc64Hasher.h
	Common/XzCrc64Init.cpp
	Common/XzCrc64Reg.cpp
	Windows/Clipboard.cpp
	Windows/Clipboard.h
	Windows/CommonDialog.cpp
	Windows/CommonDialog.h
	Windows/COM.cpp
	Windows/COM.h
	Windows/Console.cpp
	Windows/Console.h
	Windows/Control/ComboBox.cpp
	Windows/Control/ComboBox.h
	Windows/Control/CommandBar.h
	Windows/Control/Dialog.cpp
	Windows/Control/Dialog.h
	Windows/Control/Edit.h
	Windows/Control/ImageList.cpp
	Windows/Control/ImageList.h
	Windows/Control/ListView.cpp
	Windows/Control/ListView.h
	Windows/Control/ProgressBar.h
	Windows/Control/PropertyPage.cpp
	Windows/Control/PropertyPage.h
	Windows/Control/ReBar.h
	Windows/Control/Static.h
	Windows/Control/StatusBar.h
	Windows/Control/StdAfx.h
	Windows/Control/ToolBar.h
	Windows/Control/Trackbar.h
	Windows/Control/Window2.cpp
	Windows/Control/Window2.h
	Windows/Defs.h
	Windows/DLL.cpp
	Windows/DLL.h
	Windows/ErrorMsg.cpp
	Windows/ErrorMsg.h
	Windows/FileDir.cpp
	Windows/FileDir.h
	Windows/FileFind.cpp
	Windows/FileFind.h
	Windows/FileIO.cpp
	Windows/FileIO.h
	Windows/FileLink.cpp
	Windows/FileMapping.cpp
	Windows/FileMapping.h
	Windows/FileName.cpp
	Windows/FileName.h
	Windows/FileSystem.cpp
	Windows/FileSystem.h
	Windows/Handle.h
	Windows/MemoryGlobal.cpp
	Windows/MemoryGlobal.h
	Windows/MemoryLock.cpp
	Windows/MemoryLock.h
	Windows/Menu.cpp
	Windows/Menu.h
	Windows/NationalTime.cpp
	Windows/NationalTime.h
	Windows/Net.cpp
	Windows/Net.h
	Windows/NtCheck.h
	Windows/ProcessMessages.cpp
	Windows/ProcessMessages.h
	Windows/ProcessUtils.cpp
	Windows/ProcessUtils.h
	Windows/PropVariantConv.cpp
	Windows/PropVariantConv.h
	Windows/PropVariantUtils.cpp
	Windows/PropVariantUtils.h
	Windows/PropVariant.cpp
	Windows/PropVariant.h
	Windows/Registry.cpp
	Windows/Registry.h
	Windows/ResourceString.cpp
	Windows/ResourceString.h
	Windows/SecurityUtils.cpp
	Windows/SecurityUtils.h
	Windows/Shell.cpp
	Windows/Shell.h
	Windows/StdAfx.h
	Windows/Synchronization.cpp
	Windows/Synchronization.h
	Windows/SystemInfo.cpp
	Windows/SystemInfo.h
	Windows/System.cpp
	Windows/System.h
	Windows/Thread.h
	Windows/TimeUtils.cpp
	Windows/TimeUtils.h
	Windows/Window.cpp
	Windows/Window.h
)

list(TRANSFORM SEVEN_ZIP_C_SOURCE_FILES PREPEND "C/")
list(TRANSFORM SEVEN_ZIP_CPP_SOURCE_FILES PREPEND "CPP/")

source_group(TREE ${CMAKE_CURRENT_SOURCE_DIR} FILES ${SEVEN_ZIP_C_SOURCE_FILES})
source_group(TREE ${CMAKE_CURRENT_SOURCE_DIR} FILES ${SEVEN_ZIP_CPP_SOURCE_FILES})
